language: node_js
node_js:
  - 10.12
# every second counts
git:
  depth: 5
env:
  - NODE_ENV=production ESLINT_BEFORE_BUILD=false
jobs:
  include:
    - stage: test
      name: "eslint"
      cache:
        directories:
          - node_modules
      install:
        - npm install --dev
      script:
        - npm run lint -- --max-warnings=0
    - stage: test
      name: "tests"
      cache:
        directories:
          - node_modules
      install:
        - npm install --dev
      script:
        - npm run test -- --maxWorkers=2
    - stage: test
      name: "server tests"
      cache:
        directories:
          - server/node_modules
      env:
        - NODE_ENV=test
      install:
        - cd server && npm install --dev && cd ..
      script:
        - cd server && npm run test:once -- --maxWorkers=2 && cd ..
    # TODO: Code duplication calculator
    - stage: build
      services: docker
      script: docker build -f .docker/production/Dockerfile --tag wowanalyzer .
      # Reminder: deploy doesn't run on PRs
      deploy:
        provider: script
        skip_cleanup: true
        script: bash .docker/production/deploy.sh
        on:
          all_branches: true
after_failure:
  - chmod +x .travis/discord-hook/fail.sh
  - ./.travis/discord-hook/fail.sh
notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
