language: node_js
node_js:
  - 9.9.0
# every second counts
git:
  depth: 5
env:
  - NODE_ENV=production ESLINT_BEFORE_BUILD=false
jobs:
  include:
    - stage: test
      cache:
        directories:
          - node_modules
      install:
        - npm install
      script:
        - npm run lint -- --max-warnings=0
    - stage: test
      cache:
        directories:
          - node_modules
      install:
        - npm install
      script:
        - npm run test -- --maxWorkers=2
    # TODO: Code duplication calculator
    - stage: build
      services: docker
      cache:
        directories:
          - node_modules
          - server/node_modules
      install:
        - npm install
        - cd server && npm install --dev && cd ..
      script:
        - echo "> Build server"
        - cd server
        - npm run build
        - echo "> The server has already been built so we no longer need the devDependencies (reduces the final bundle size)"
        - npm prune --production
        - cd ..
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
          	echo "> Disabling sourcemap generation to save build time, this is a PR so won't be deployed anyway.";
          	export GENERATE_SOURCEMAP=false;
          fi
        - echo "> Build app"
        - npm run build
      # Reminder: deploy doesn't run on PRs
      deploy:
        provider: script
        skip_cleanup: true
        script: bash .travis/deploy.sh
        on:
          all_branches: true
# TODO After getting the build right:
#after_failure:
#  - chmod +x .travis/discord-hook/fail.sh
#  - ./.travis/discord-hook/fail.sh
#notifications:
#  webhooks: https://www.travisbuddy.com/
#  on_success: never
