version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: wowanalyzer-dev
    ports:
     - 3000:3000
     - 35729:35729
    volumes:
      - .:/usr/src/wowanalyzer
  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: wowanalyzer-prod
    ports:
     - 3000:3000
  database:
    image: "mariadb:10.3"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw
    ports:
      - '4306:3306' # don't conflict with existing MySQL servers
