version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: wowanalyzer-dev
    ports:
     - 3000:3000
     - 35729:35729
    volumes:
      - .:/usr/src/wowanalyzer/
      - /usr/src/wowanalyzer/node_modules/
  server-dev:
    build:
      context: .
      dockerfile: Dockerfile.server-dev
    container_name: wowanalyzer-server-dev
    environment:
     - MYSQL_HOST=database
     - MYSQL_ROOT_PASSWORD=my-secret-pw
    ports:
     - 3000:3000
    volumes:
      - ./server:/usr/src/wowanalyzer/server/
  package:
    build:
      context: .
      dockerfile: Dockerfile.package
    container_name: wowanalyzer
    environment:
     - MYSQL_HOST=database
     - MYSQL_ROOT_PASSWORD=my-secret-pw
    ports:
     - 3000:3000
  database:
    image: "mariadb:10.3"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--max_allowed_packet=64M']
    environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw
     - MYSQL_DATABASE=wowanalyzer
    restart: always
    ports:
     - 4306:3306
